//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace GalArc.Properties {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("GalArc.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   重写当前线程的 CurrentUICulture 属性，对
        ///   使用此强类型资源类的所有资源查找执行重写。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 Check 的本地化字符串。
        /// </summary>
        internal static string ab_btn_Check {
            get {
                return ResourceManager.GetString("ab_btn_Check", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Download 的本地化字符串。
        /// </summary>
        internal static string ab_btn_Download {
            get {
                return ResourceManager.GetString("ab_btn_Download", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Engine Name 的本地化字符串。
        /// </summary>
        internal static string ab_col_EngineName {
            get {
                return ResourceManager.GetString("ab_col_EngineName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Pack Format 的本地化字符串。
        /// </summary>
        internal static string ab_col_PackFormat {
            get {
                return ResourceManager.GetString("ab_col_PackFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Unpack Format 的本地化字符串。
        /// </summary>
        internal static string ab_col_UnpackFormat {
            get {
                return ResourceManager.GetString("ab_col_UnpackFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 About 的本地化字符串。
        /// </summary>
        internal static string ab_gb_About {
            get {
                return ResourceManager.GetString("ab_gb_About", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Supported Formats 的本地化字符串。
        /// </summary>
        internal static string ab_gb_Format {
            get {
                return ResourceManager.GetString("ab_gb_Format", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Update 的本地化字符串。
        /// </summary>
        internal static string ab_gb_Update {
            get {
                return ResourceManager.GetString("ab_gb_Update", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Current Version: 的本地化字符串。
        /// </summary>
        internal static string ab_lb_CurrentVersion {
            get {
                return ResourceManager.GetString("ab_lb_CurrentVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Unknown 的本地化字符串。
        /// </summary>
        internal static string ab_lb_LatestVer {
            get {
                return ResourceManager.GetString("ab_lb_LatestVer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Latest Version: 的本地化字符串。
        /// </summary>
        internal static string ab_lb_LatestVersion {
            get {
                return ResourceManager.GetString("ab_lb_LatestVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Search: 的本地化字符串。
        /// </summary>
        internal static string ab_lb_Search {
            get {
                return ResourceManager.GetString("ab_lb_Search", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Report Issue 的本地化字符串。
        /// </summary>
        internal static string ab_link_Issue {
            get {
                return ResourceManager.GetString("ab_link_Issue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Development Site 的本地化字符串。
        /// </summary>
        internal static string ab_link_Site {
            get {
                return ResourceManager.GetString("ab_link_Site", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 About 的本地化字符串。
        /// </summary>
        internal static string main_aboutPage_Text {
            get {
                return ResourceManager.GetString("main_aboutPage_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Option 的本地化字符串。
        /// </summary>
        internal static string main_optionPage_Text {
            get {
                return ResourceManager.GetString("main_optionPage_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Pack 的本地化字符串。
        /// </summary>
        internal static string main_packPage_Text {
            get {
                return ResourceManager.GetString("main_packPage_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Unpack 的本地化字符串。
        /// </summary>
        internal static string main_unpackPage_Text {
            get {
                return ResourceManager.GetString("main_unpackPage_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Always on top 的本地化字符串。
        /// </summary>
        internal static string op_chkbx_OnTop {
            get {
                return ResourceManager.GetString("op_chkbx_OnTop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Language 的本地化字符串。
        /// </summary>
        internal static string op_lb_Lang {
            get {
                return ResourceManager.GetString("op_lb_Lang", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Clear 的本地化字符串。
        /// </summary>
        internal static string pa_btn_Clear {
            get {
                return ResourceManager.GetString("pa_btn_Clear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Pack 的本地化字符串。
        /// </summary>
        internal static string pa_btn_Pack {
            get {
                return ResourceManager.GetString("pa_btn_Pack", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Log 的本地化字符串。
        /// </summary>
        internal static string pa_chkbx_Log {
            get {
                return ResourceManager.GetString("pa_chkbx_Log", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Match 的本地化字符串。
        /// </summary>
        internal static string pa_chkbx_Match {
            get {
                return ResourceManager.GetString("pa_chkbx_Match", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Pack Option 的本地化字符串。
        /// </summary>
        internal static string pa_gb_Option {
            get {
                return ResourceManager.GetString("pa_gb_Option", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Name Encoding 的本地化字符串。
        /// </summary>
        internal static string pa_lb_Encoding {
            get {
                return ResourceManager.GetString("pa_lb_Encoding", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Engine 的本地化字符串。
        /// </summary>
        internal static string pa_lb_Engine {
            get {
                return ResourceManager.GetString("pa_lb_Engine", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Format 的本地化字符串。
        /// </summary>
        internal static string pa_lb_Format {
            get {
                return ResourceManager.GetString("pa_lb_Format", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Input Folder 的本地化字符串。
        /// </summary>
        internal static string pa_lb_InputFolder {
            get {
                return ResourceManager.GetString("pa_lb_InputFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Output File 的本地化字符串。
        /// </summary>
        internal static string pa_lb_OutputFile {
            get {
                return ResourceManager.GetString("pa_lb_OutputFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Pack Format 的本地化字符串。
        /// </summary>
        internal static string pa_lb_PackFormat {
            get {
                return ResourceManager.GetString("pa_lb_PackFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Version 的本地化字符串。
        /// </summary>
        internal static string pa_lb_Version {
            get {
                return ResourceManager.GetString("pa_lb_Version", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Clear 的本地化字符串。
        /// </summary>
        internal static string un_btn_Clear {
            get {
                return ResourceManager.GetString("un_btn_Clear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Unpack 的本地化字符串。
        /// </summary>
        internal static string un_btn_Unpack {
            get {
                return ResourceManager.GetString("un_btn_Unpack", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Decrypt Scripts 的本地化字符串。
        /// </summary>
        internal static string un_chkbx_DecScr {
            get {
                return ResourceManager.GetString("un_chkbx_DecScr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Log 的本地化字符串。
        /// </summary>
        internal static string un_chkbx_Log {
            get {
                return ResourceManager.GetString("un_chkbx_Log", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Match 的本地化字符串。
        /// </summary>
        internal static string un_chkbx_Match {
            get {
                return ResourceManager.GetString("un_chkbx_Match", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Unpack Option 的本地化字符串。
        /// </summary>
        internal static string un_gb_Option {
            get {
                return ResourceManager.GetString("un_gb_Option", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Name Encoding 的本地化字符串。
        /// </summary>
        internal static string un_lb_Encoding {
            get {
                return ResourceManager.GetString("un_lb_Encoding", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Engine 的本地化字符串。
        /// </summary>
        internal static string un_lb_Engine {
            get {
                return ResourceManager.GetString("un_lb_Engine", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Format 的本地化字符串。
        /// </summary>
        internal static string un_lb_Format {
            get {
                return ResourceManager.GetString("un_lb_Format", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Input File 的本地化字符串。
        /// </summary>
        internal static string un_lb_InputFile {
            get {
                return ResourceManager.GetString("un_lb_InputFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Output Folder 的本地化字符串。
        /// </summary>
        internal static string un_lb_OutputFolder {
            get {
                return ResourceManager.GetString("un_lb_OutputFolder", resourceCulture);
            }
        }
    }
}
