//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace GalArc.Properties {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("GalArc.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   重写当前线程的 CurrentUICulture 属性，对
        ///   使用此强类型资源类的所有资源查找执行重写。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 About 的本地化字符串。
        /// </summary>
        internal static string ab_gb_About {
            get {
                return ResourceManager.GetString("ab_gb_About", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Supported Formats 的本地化字符串。
        /// </summary>
        internal static string ab_gb_Format {
            get {
                return ResourceManager.GetString("ab_gb_Format", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Update 的本地化字符串。
        /// </summary>
        internal static string ab_gb_Update {
            get {
                return ResourceManager.GetString("ab_gb_Update", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Current Version: 的本地化字符串。
        /// </summary>
        internal static string ab_lb_CurrentVersion {
            get {
                return ResourceManager.GetString("ab_lb_CurrentVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Unknown 的本地化字符串。
        /// </summary>
        internal static string ab_lb_LatestVer {
            get {
                return ResourceManager.GetString("ab_lb_LatestVer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Latest Version: 的本地化字符串。
        /// </summary>
        internal static string ab_lb_LatestVersion {
            get {
                return ResourceManager.GetString("ab_lb_LatestVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Search: 的本地化字符串。
        /// </summary>
        internal static string ab_lb_Search {
            get {
                return ResourceManager.GetString("ab_lb_Search", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Report Issue 的本地化字符串。
        /// </summary>
        internal static string ab_link_Issue {
            get {
                return ResourceManager.GetString("ab_link_Issue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Development Site 的本地化字符串。
        /// </summary>
        internal static string ab_link_Site {
            get {
                return ResourceManager.GetString("ab_link_Site", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Engine Name 的本地化字符串。
        /// </summary>
        internal static string columnEngineName {
            get {
                return ResourceManager.GetString("columnEngineName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Pack Format 的本地化字符串。
        /// </summary>
        internal static string columnPackFormat {
            get {
                return ResourceManager.GetString("columnPackFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Unpack Format 的本地化字符串。
        /// </summary>
        internal static string columnUnpackFormat {
            get {
                return ResourceManager.GetString("columnUnpackFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Version {0} 的本地化字符串。
        /// </summary>
        internal static string lbVersion {
            get {
                return ResourceManager.GetString("lbVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 About 的本地化字符串。
        /// </summary>
        internal static string main_aboutPage_Text {
            get {
                return ResourceManager.GetString("main_aboutPage_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Option 的本地化字符串。
        /// </summary>
        internal static string main_optionPage_Text {
            get {
                return ResourceManager.GetString("main_optionPage_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Pack 的本地化字符串。
        /// </summary>
        internal static string main_packPage_Text {
            get {
                return ResourceManager.GetString("main_packPage_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Unpack 的本地化字符串。
        /// </summary>
        internal static string main_unpackPage_Text {
            get {
                return ResourceManager.GetString("main_unpackPage_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 General 的本地化字符串。
        /// </summary>
        internal static string nodeGeneral {
            get {
                return ResourceManager.GetString("nodeGeneral", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Preference 的本地化字符串。
        /// </summary>
        internal static string nodePreference {
            get {
                return ResourceManager.GetString("nodePreference", resourceCulture);
            }
        }
    }
}
