//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GalArc.I18n {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class GuiStrings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal GuiStrings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("GalArc.I18n.GuiStrings", typeof(GuiStrings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About.
        /// </summary>
        public static string About {
            get {
                return ResourceManager.GetString("About", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Address.
        /// </summary>
        public static string Address {
            get {
                return ResourceManager.GetString("Address", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Brutal Force.
        /// </summary>
        public static string BrutalForce {
            get {
                return ResourceManager.GetString("BrutalForce", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Continue on Error.
        /// </summary>
        public static string ButtonContinue {
            get {
                return ResourceManager.GetString("ButtonContinue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start.
        /// </summary>
        public static string ButtonStart {
            get {
                return ResourceManager.GetString("ButtonStart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        public static string Cancel {
            get {
                return ResourceManager.GetString("Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Check.
        /// </summary>
        public static string Check {
            get {
                return ResourceManager.GetString("Check", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Check For Updates.
        /// </summary>
        public static string CheckUpdates {
            get {
                return ResourceManager.GetString("CheckUpdates", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Compress Contents.
        /// </summary>
        public static string CompressContents {
            get {
                return ResourceManager.GetString("CompressContents", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Compress Index.
        /// </summary>
        public static string CompressIndex {
            get {
                return ResourceManager.GetString("CompressIndex", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Compression Method.
        /// </summary>
        public static string CompressionMethod {
            get {
                return ResourceManager.GetString("CompressionMethod", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Compute Checksum.
        /// </summary>
        public static string ComputeChecksum {
            get {
                return ResourceManager.GetString("ComputeChecksum", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Configures marked with * will take effect after a restart..
        /// </summary>
        public static string ConfigNeedRestart {
            get {
                return ResourceManager.GetString("ConfigNeedRestart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copy.
        /// </summary>
        public static string Copy {
            get {
                return ResourceManager.GetString("Copy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dark.
        /// </summary>
        public static string Dark {
            get {
                return ResourceManager.GetString("Dark", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Database.
        /// </summary>
        public static string Database {
            get {
                return ResourceManager.GetString("Database", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Database Path.
        /// </summary>
        public static string DatabasePath {
            get {
                return ResourceManager.GetString("DatabasePath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Decrypt Scripts.
        /// </summary>
        public static string DecryptScripts {
            get {
                return ResourceManager.GetString("DecryptScripts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Default encryption scheme.
        /// </summary>
        public static string DefaultEnc {
            get {
                return ResourceManager.GetString("DefaultEnc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Encoding.
        /// </summary>
        public static string Encoding {
            get {
                return ResourceManager.GetString("Encoding", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Encrypt Scripts.
        /// </summary>
        public static string EncryptScripts {
            get {
                return ResourceManager.GetString("EncryptScripts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exit.
        /// </summary>
        public static string Exit {
            get {
                return ResourceManager.GetString("Exit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File.
        /// </summary>
        public static string File {
            get {
                return ResourceManager.GetString("File", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to General.
        /// </summary>
        public static string General {
            get {
                return ResourceManager.GetString("General", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Additional Options.
        /// </summary>
        public static string GroupAdditional {
            get {
                return ResourceManager.GetString("GroupAdditional", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Format.
        /// </summary>
        public static string GroupFormat {
            get {
                return ResourceManager.GetString("GroupFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Format Options.
        /// </summary>
        public static string GroupFormatOptions {
            get {
                return ResourceManager.GetString("GroupFormatOptions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Input.
        /// </summary>
        public static string GroupInput {
            get {
                return ResourceManager.GetString("GroupInput", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Log.
        /// </summary>
        public static string GroupLog {
            get {
                return ResourceManager.GetString("GroupLog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Operation.
        /// </summary>
        public static string GroupOperation {
            get {
                return ResourceManager.GetString("GroupOperation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Output.
        /// </summary>
        public static string GroupOutput {
            get {
                return ResourceManager.GetString("GroupOutput", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Path.
        /// </summary>
        public static string GroupPath {
            get {
                return ResourceManager.GetString("GroupPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Progress.
        /// </summary>
        public static string GroupProgress {
            get {
                return ResourceManager.GetString("GroupProgress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hash Version.
        /// </summary>
        public static string HashVersion {
            get {
                return ResourceManager.GetString("HashVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Help.
        /// </summary>
        public static string Help {
            get {
                return ResourceManager.GetString("Help", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Language.
        /// </summary>
        public static string Language {
            get {
                return ResourceManager.GetString("Language", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Light.
        /// </summary>
        public static string Light {
            get {
                return ResourceManager.GetString("Light", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Log File Path.
        /// </summary>
        public static string LogFilePath {
            get {
                return ResourceManager.GetString("LogFilePath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Logging.
        /// </summary>
        public static string Logging {
            get {
                return ResourceManager.GetString("Logging", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Major Version.
        /// </summary>
        public static string MajorVersion {
            get {
                return ResourceManager.GetString("MajorVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Match Paths.
        /// </summary>
        public static string MatchPaths {
            get {
                return ResourceManager.GetString("MatchPaths", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Minor Version.
        /// </summary>
        public static string MinorVersion {
            get {
                return ResourceManager.GetString("MinorVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No Encryption.
        /// </summary>
        public static string NoEncryption {
            get {
                return ResourceManager.GetString("NoEncryption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to None.
        /// </summary>
        public static string None {
            get {
                return ResourceManager.GetString("None", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open Url.
        /// </summary>
        public static string OpenUrl {
            get {
                return ResourceManager.GetString("OpenUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pack.
        /// </summary>
        public static string OperationPack {
            get {
                return ResourceManager.GetString("OperationPack", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unpack.
        /// </summary>
        public static string OperationUnpack {
            get {
                return ResourceManager.GetString("OperationUnpack", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Optional.
        /// </summary>
        public static string Optional {
            get {
                return ResourceManager.GetString("Optional", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Original Archive Path.
        /// </summary>
        public static string OriginalArchive {
            get {
                return ResourceManager.GetString("OriginalArchive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password.
        /// </summary>
        public static string Password {
            get {
                return ResourceManager.GetString("Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Path.
        /// </summary>
        public static string Path {
            get {
                return ResourceManager.GetString("Path", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Port.
        /// </summary>
        public static string Port {
            get {
                return ResourceManager.GetString("Port", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Proxy.
        /// </summary>
        public static string Proxy {
            get {
                return ResourceManager.GetString("Proxy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Proxy Type.
        /// </summary>
        public static string ProxyType {
            get {
                return ResourceManager.GetString("ProxyType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reset.
        /// </summary>
        public static string Reset {
            get {
                return ResourceManager.GetString("Reset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save Hash.
        /// </summary>
        public static string SaveHash {
            get {
                return ResourceManager.GetString("SaveHash", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save Key.
        /// </summary>
        public static string SaveKey {
            get {
                return ResourceManager.GetString("SaveKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save Logs.
        /// </summary>
        public static string SaveLogs {
            get {
                return ResourceManager.GetString("SaveLogs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Seed.
        /// </summary>
        public static string Seed {
            get {
                return ResourceManager.GetString("Seed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Segment Contents.
        /// </summary>
        public static string SegContent {
            get {
                return ResourceManager.GetString("SegContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select encryption scheme.
        /// </summary>
        public static string SelectEncScheme {
            get {
                return ResourceManager.GetString("SelectEncScheme", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Set Input Path.
        /// </summary>
        public static string SetInput {
            get {
                return ResourceManager.GetString("SetInput", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Set Output Path.
        /// </summary>
        public static string SetOutput {
            get {
                return ResourceManager.GetString("SetOutput", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        public static string Settings {
            get {
                return ResourceManager.GetString("Settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Source URL.
        /// </summary>
        public static string SourceURL {
            get {
                return ResourceManager.GetString("SourceURL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Specify Index Offset.
        /// </summary>
        public static string SpecifyIndexOffset {
            get {
                return ResourceManager.GetString("SpecifyIndexOffset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Status.
        /// </summary>
        public static string Status {
            get {
                return ResourceManager.GetString("Status", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to System.
        /// </summary>
        public static string System {
            get {
                return ResourceManager.GetString("System", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Theme.
        /// </summary>
        public static string Theme {
            get {
                return ResourceManager.GetString("Theme", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Try every encryption scheme.
        /// </summary>
        public static string TryEveryEnc {
            get {
                return ResourceManager.GetString("TryEveryEnc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update.
        /// </summary>
        public static string Update {
            get {
                return ResourceManager.GetString("Update", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Username.
        /// </summary>
        public static string Username {
            get {
                return ResourceManager.GetString("Username", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Version.
        /// </summary>
        public static string Version {
            get {
                return ResourceManager.GetString("Version", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Input File Path (Support wildcard).
        /// </summary>
        public static string WaterInputFile {
            get {
                return ResourceManager.GetString("WaterInputFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Input Folder Path.
        /// </summary>
        public static string WaterInputFolder {
            get {
                return ResourceManager.GetString("WaterInputFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Output File Path.
        /// </summary>
        public static string WaterOutputFile {
            get {
                return ResourceManager.GetString("WaterOutputFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Output Folder Path.
        /// </summary>
        public static string WaterOutputFolder {
            get {
                return ResourceManager.GetString("WaterOutputFolder", resourceCulture);
            }
        }
    }
}
