//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace GalArc.I18n {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class GuiStrings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal GuiStrings() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("GalArc.I18n.GuiStrings", typeof(GuiStrings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   重写当前线程的 CurrentUICulture 属性，对
        ///   使用此强类型资源类的所有资源查找执行重写。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 About 的本地化字符串。
        /// </summary>
        public static string About {
            get {
                return ResourceManager.GetString("About", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Address 的本地化字符串。
        /// </summary>
        public static string Address {
            get {
                return ResourceManager.GetString("Address", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Brutal Force 的本地化字符串。
        /// </summary>
        public static string BrutalForce {
            get {
                return ResourceManager.GetString("BrutalForce", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Continue on Error 的本地化字符串。
        /// </summary>
        public static string ButtonContinue {
            get {
                return ResourceManager.GetString("ButtonContinue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Start 的本地化字符串。
        /// </summary>
        public static string ButtonStart {
            get {
                return ResourceManager.GetString("ButtonStart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Cancel 的本地化字符串。
        /// </summary>
        public static string Cancel {
            get {
                return ResourceManager.GetString("Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Check 的本地化字符串。
        /// </summary>
        public static string Check {
            get {
                return ResourceManager.GetString("Check", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Check For Updates 的本地化字符串。
        /// </summary>
        public static string CheckUpdates {
            get {
                return ResourceManager.GetString("CheckUpdates", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Compress Contents 的本地化字符串。
        /// </summary>
        public static string CompressContents {
            get {
                return ResourceManager.GetString("CompressContents", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Compress Index 的本地化字符串。
        /// </summary>
        public static string CompressIndex {
            get {
                return ResourceManager.GetString("CompressIndex", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Compression Method 的本地化字符串。
        /// </summary>
        public static string CompressionMethod {
            get {
                return ResourceManager.GetString("CompressionMethod", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Compute Checksum 的本地化字符串。
        /// </summary>
        public static string ComputeChecksum {
            get {
                return ResourceManager.GetString("ComputeChecksum", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Configures marked with * will take effect after a restart. 的本地化字符串。
        /// </summary>
        public static string ConfigNeedRestart {
            get {
                return ResourceManager.GetString("ConfigNeedRestart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Copy 的本地化字符串。
        /// </summary>
        public static string Copy {
            get {
                return ResourceManager.GetString("Copy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Dark 的本地化字符串。
        /// </summary>
        public static string Dark {
            get {
                return ResourceManager.GetString("Dark", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Database 的本地化字符串。
        /// </summary>
        public static string Database {
            get {
                return ResourceManager.GetString("Database", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Database Path 的本地化字符串。
        /// </summary>
        public static string DatabasePath {
            get {
                return ResourceManager.GetString("DatabasePath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Decrypt Scripts 的本地化字符串。
        /// </summary>
        public static string DecryptScripts {
            get {
                return ResourceManager.GetString("DecryptScripts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Default encryption scheme 的本地化字符串。
        /// </summary>
        public static string DefaultEnc {
            get {
                return ResourceManager.GetString("DefaultEnc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Encoding 的本地化字符串。
        /// </summary>
        public static string Encoding {
            get {
                return ResourceManager.GetString("Encoding", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Encrypt Scripts 的本地化字符串。
        /// </summary>
        public static string EncryptScripts {
            get {
                return ResourceManager.GetString("EncryptScripts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Exit 的本地化字符串。
        /// </summary>
        public static string Exit {
            get {
                return ResourceManager.GetString("Exit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 File 的本地化字符串。
        /// </summary>
        public static string File {
            get {
                return ResourceManager.GetString("File", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 General 的本地化字符串。
        /// </summary>
        public static string General {
            get {
                return ResourceManager.GetString("General", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Additional Options 的本地化字符串。
        /// </summary>
        public static string GroupAdditional {
            get {
                return ResourceManager.GetString("GroupAdditional", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Format 的本地化字符串。
        /// </summary>
        public static string GroupFormat {
            get {
                return ResourceManager.GetString("GroupFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Format Options 的本地化字符串。
        /// </summary>
        public static string GroupFormatOptions {
            get {
                return ResourceManager.GetString("GroupFormatOptions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Input 的本地化字符串。
        /// </summary>
        public static string GroupInput {
            get {
                return ResourceManager.GetString("GroupInput", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Log 的本地化字符串。
        /// </summary>
        public static string GroupLog {
            get {
                return ResourceManager.GetString("GroupLog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Operation 的本地化字符串。
        /// </summary>
        public static string GroupOperation {
            get {
                return ResourceManager.GetString("GroupOperation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Output 的本地化字符串。
        /// </summary>
        public static string GroupOutput {
            get {
                return ResourceManager.GetString("GroupOutput", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Path 的本地化字符串。
        /// </summary>
        public static string GroupPath {
            get {
                return ResourceManager.GetString("GroupPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Progress 的本地化字符串。
        /// </summary>
        public static string GroupProgress {
            get {
                return ResourceManager.GetString("GroupProgress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Hash Version 的本地化字符串。
        /// </summary>
        public static string HashVersion {
            get {
                return ResourceManager.GetString("HashVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Help 的本地化字符串。
        /// </summary>
        public static string Help {
            get {
                return ResourceManager.GetString("Help", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 HTTP 的本地化字符串。
        /// </summary>
        public static string HTTP {
            get {
                return ResourceManager.GetString("HTTP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Index Offset 的本地化字符串。
        /// </summary>
        public static string IndexOffset {
            get {
                return ResourceManager.GetString("IndexOffset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Language 的本地化字符串。
        /// </summary>
        public static string Language {
            get {
                return ResourceManager.GetString("Language", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Light 的本地化字符串。
        /// </summary>
        public static string Light {
            get {
                return ResourceManager.GetString("Light", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Log File Path 的本地化字符串。
        /// </summary>
        public static string LogFilePath {
            get {
                return ResourceManager.GetString("LogFilePath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Logging 的本地化字符串。
        /// </summary>
        public static string Logging {
            get {
                return ResourceManager.GetString("Logging", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Major Version 的本地化字符串。
        /// </summary>
        public static string MajorVersion {
            get {
                return ResourceManager.GetString("MajorVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Match Paths 的本地化字符串。
        /// </summary>
        public static string MatchPaths {
            get {
                return ResourceManager.GetString("MatchPaths", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Minor Version 的本地化字符串。
        /// </summary>
        public static string MinorVersion {
            get {
                return ResourceManager.GetString("MinorVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 No Encryption 的本地化字符串。
        /// </summary>
        public static string NoEncryption {
            get {
                return ResourceManager.GetString("NoEncryption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 None 的本地化字符串。
        /// </summary>
        public static string None {
            get {
                return ResourceManager.GetString("None", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Open Url 的本地化字符串。
        /// </summary>
        public static string OpenUrl {
            get {
                return ResourceManager.GetString("OpenUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Pack 的本地化字符串。
        /// </summary>
        public static string OperationPack {
            get {
                return ResourceManager.GetString("OperationPack", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Unpack 的本地化字符串。
        /// </summary>
        public static string OperationUnpack {
            get {
                return ResourceManager.GetString("OperationUnpack", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Optional 的本地化字符串。
        /// </summary>
        public static string Optional {
            get {
                return ResourceManager.GetString("Optional", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Original Archive Path 的本地化字符串。
        /// </summary>
        public static string OriginalArchive {
            get {
                return ResourceManager.GetString("OriginalArchive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Password 的本地化字符串。
        /// </summary>
        public static string Password {
            get {
                return ResourceManager.GetString("Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Path 的本地化字符串。
        /// </summary>
        public static string Path {
            get {
                return ResourceManager.GetString("Path", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Port 的本地化字符串。
        /// </summary>
        public static string Port {
            get {
                return ResourceManager.GetString("Port", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Proxy 的本地化字符串。
        /// </summary>
        public static string Proxy {
            get {
                return ResourceManager.GetString("Proxy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Proxy Type 的本地化字符串。
        /// </summary>
        public static string ProxyType {
            get {
                return ResourceManager.GetString("ProxyType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Reset 的本地化字符串。
        /// </summary>
        public static string Reset {
            get {
                return ResourceManager.GetString("Reset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Save Hash 的本地化字符串。
        /// </summary>
        public static string SaveHash {
            get {
                return ResourceManager.GetString("SaveHash", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Save Key 的本地化字符串。
        /// </summary>
        public static string SaveKey {
            get {
                return ResourceManager.GetString("SaveKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Save Logs 的本地化字符串。
        /// </summary>
        public static string SaveLogs {
            get {
                return ResourceManager.GetString("SaveLogs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Seed 的本地化字符串。
        /// </summary>
        public static string Seed {
            get {
                return ResourceManager.GetString("Seed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Segment Contents 的本地化字符串。
        /// </summary>
        public static string SegContent {
            get {
                return ResourceManager.GetString("SegContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Please select encryption scheme 的本地化字符串。
        /// </summary>
        public static string SelectEncScheme {
            get {
                return ResourceManager.GetString("SelectEncScheme", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Set Input Path 的本地化字符串。
        /// </summary>
        public static string SetInput {
            get {
                return ResourceManager.GetString("SetInput", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Set Output Path 的本地化字符串。
        /// </summary>
        public static string SetOutput {
            get {
                return ResourceManager.GetString("SetOutput", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Settings 的本地化字符串。
        /// </summary>
        public static string Settings {
            get {
                return ResourceManager.GetString("Settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 SOCKS 的本地化字符串。
        /// </summary>
        public static string SOCKS {
            get {
                return ResourceManager.GetString("SOCKS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Source URL 的本地化字符串。
        /// </summary>
        public static string SourceURL {
            get {
                return ResourceManager.GetString("SourceURL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Specify Index Offset 的本地化字符串。
        /// </summary>
        public static string SpecifyIndexOffset {
            get {
                return ResourceManager.GetString("SpecifyIndexOffset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Status 的本地化字符串。
        /// </summary>
        public static string Status {
            get {
                return ResourceManager.GetString("Status", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 System 的本地化字符串。
        /// </summary>
        public static string System {
            get {
                return ResourceManager.GetString("System", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Theme 的本地化字符串。
        /// </summary>
        public static string Theme {
            get {
                return ResourceManager.GetString("Theme", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Try every encryption scheme 的本地化字符串。
        /// </summary>
        public static string TryEveryEnc {
            get {
                return ResourceManager.GetString("TryEveryEnc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Update 的本地化字符串。
        /// </summary>
        public static string Update {
            get {
                return ResourceManager.GetString("Update", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Username 的本地化字符串。
        /// </summary>
        public static string Username {
            get {
                return ResourceManager.GetString("Username", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Version 的本地化字符串。
        /// </summary>
        public static string Version {
            get {
                return ResourceManager.GetString("Version", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Input File Path (Support wildcard) 的本地化字符串。
        /// </summary>
        public static string WaterInputFile {
            get {
                return ResourceManager.GetString("WaterInputFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Input Folder Path 的本地化字符串。
        /// </summary>
        public static string WaterInputFolder {
            get {
                return ResourceManager.GetString("WaterInputFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Output File Path 的本地化字符串。
        /// </summary>
        public static string WaterOutputFile {
            get {
                return ResourceManager.GetString("WaterOutputFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Output Folder Path 的本地化字符串。
        /// </summary>
        public static string WaterOutputFolder {
            get {
                return ResourceManager.GetString("WaterOutputFolder", resourceCulture);
            }
        }
    }
}
