//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace GalArc.I18n {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class MsgStrings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal MsgStrings() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("GalArc.I18n.MsgStrings", typeof(MsgStrings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   重写当前线程的 CurrentUICulture 属性，对
        ///   使用此强类型资源类的所有资源查找执行重写。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 Brutal forcing... 的本地化字符串。
        /// </summary>
        internal static string BrutalForcing {
            get {
                return ResourceManager.GetString("BrutalForcing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Checking for updates... 的本地化字符串。
        /// </summary>
        internal static string CheckingUpdates {
            get {
                return ResourceManager.GetString("CheckingUpdates", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Compression method: {0} 的本地化字符串。
        /// </summary>
        internal static string CompressionMethod {
            get {
                return ResourceManager.GetString("CompressionMethod", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Configuring settings... 的本地化字符串。
        /// </summary>
        internal static string ConfiguringSettings {
            get {
                return ResourceManager.GetString("ConfiguringSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Continue... 的本地化字符串。
        /// </summary>
        internal static string ContinueOnError {
            get {
                return ResourceManager.GetString("ContinueOnError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Current Version: {0} 的本地化字符串。
        /// </summary>
        internal static string CurrentVersion {
            get {
                return ResourceManager.GetString("CurrentVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Decrypting {0}... 的本地化字符串。
        /// </summary>
        internal static string Decrypting {
            get {
                return ResourceManager.GetString("Decrypting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Encrypting {0}... 的本地化字符串。
        /// </summary>
        internal static string Encrypting {
            get {
                return ResourceManager.GetString("Encrypting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 An error occurred during the update check: {0} 的本地化字符串。
        /// </summary>
        internal static string ErrorCheckingUpdates {
            get {
                return ResourceManager.GetString("ErrorCheckingUpdates", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Path contains invalid characters. Switching the encoding in the settings might work. 的本地化字符串。
        /// </summary>
        internal static string ErrorContainsInvalid {
            get {
                return ResourceManager.GetString("ErrorContainsInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Decompression failed. 的本地化字符串。
        /// </summary>
        internal static string ErrorDecompressFailed {
            get {
                return ResourceManager.GetString("ErrorDecompressFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Decryption failed. 的本地化字符串。
        /// </summary>
        internal static string ErrorDecScrFailed {
            get {
                return ResourceManager.GetString("ErrorDecScrFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Folder specified does not exist. 的本地化字符串。
        /// </summary>
        internal static string ErrorDirNotFound {
            get {
                return ResourceManager.GetString("ErrorDirNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Encryption failed. 的本地化字符串。
        /// </summary>
        internal static string ErrorEncScrFailed {
            get {
                return ResourceManager.GetString("ErrorEncScrFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 File specified does not exist. 的本地化字符串。
        /// </summary>
        internal static string ErrorFileNotFound {
            get {
                return ResourceManager.GetString("ErrorFileNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Invalid archive. 的本地化字符串。
        /// </summary>
        internal static string ErrorInvalidArchive {
            get {
                return ResourceManager.GetString("ErrorInvalidArchive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Invalid archive: {0} 的本地化字符串。
        /// </summary>
        internal static string ErrorInvalidArchiveCaption {
            get {
                return ResourceManager.GetString("ErrorInvalidArchiveCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Invalid encryption scheme. 的本地化字符串。
        /// </summary>
        internal static string ErrorInvalidScheme {
            get {
                return ResourceManager.GetString("ErrorInvalidScheme", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Unknown or unsupported archive version. 的本地化字符串。
        /// </summary>
        internal static string ErrorInvalidVersion {
            get {
                return ResourceManager.GetString("ErrorInvalidVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 This version of archive is temporarily not supported. 的本地化字符串。
        /// </summary>
        internal static string ErrorInvalidVersionNotSupported {
            get {
                return ResourceManager.GetString("ErrorInvalidVersionNotSupported", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Unsupported version: {0} 的本地化字符串。
        /// </summary>
        internal static string ErrorInvalidVersionNotSupportedWithMsg {
            get {
                return ResourceManager.GetString("ErrorInvalidVersionNotSupportedWithMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Unknown version. 的本地化字符串。
        /// </summary>
        internal static string ErrorInvalidVersionUnknown {
            get {
                return ResourceManager.GetString("ErrorInvalidVersionUnknown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Unknown version: {0} 的本地化字符串。
        /// </summary>
        internal static string ErrorInvalidVersionUnknownWithMsg {
            get {
                return ResourceManager.GetString("ErrorInvalidVersionUnknownWithMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Unknown or not supported archive version: {0} 的本地化字符串。
        /// </summary>
        internal static string ErrorInvalidVersionWithMsg {
            get {
                return ResourceManager.GetString("ErrorInvalidVersionWithMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Failed to open url: {0} 的本地化字符串。
        /// </summary>
        internal static string ErrorOpenUrl {
            get {
                return ResourceManager.GetString("ErrorOpenUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 An error occurred during operation: {0} 的本地化字符串。
        /// </summary>
        internal static string ErrorOperation {
            get {
                return ResourceManager.GetString("ErrorOperation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Original {0} file not found in the same directory. 的本地化字符串。
        /// </summary>
        internal static string ErrorOriginalFileNotFound {
            get {
                return ResourceManager.GetString("ErrorOriginalFileNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 {0} file not found in the same directory. 的本地化字符串。
        /// </summary>
        internal static string ErrorSpecifiedFileNotFound {
            get {
                return ResourceManager.GetString("ErrorSpecifiedFileNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Index Offset 的本地化字符串。
        /// </summary>
        internal static string IndexOffset {
            get {
                return ResourceManager.GetString("IndexOffset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Inner exception: {0} 的本地化字符串。
        /// </summary>
        internal static string InnerException {
            get {
                return ResourceManager.GetString("InnerException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Key found: {0} 的本地化字符串。
        /// </summary>
        internal static string KeyFound {
            get {
                return ResourceManager.GetString("KeyFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Key not found. 的本地化字符串。
        /// </summary>
        internal static string KeyNotFound {
            get {
                return ResourceManager.GetString("KeyNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 LatestVersion: {0} 的本地化字符串。
        /// </summary>
        internal static string LatestVersion {
            get {
                return ResourceManager.GetString("LatestVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Matched game: {0} 的本地化字符串。
        /// </summary>
        internal static string MatchedGame {
            get {
                return ResourceManager.GetString("MatchedGame", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The file has been encrypted. Please choose appropriate scheme. 的本地化字符串。
        /// </summary>
        internal static string NeedDec {
            get {
                return ResourceManager.GetString("NeedDec", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Operation cancelled. 的本地化字符串。
        /// </summary>
        internal static string OperationCancelled {
            get {
                return ResourceManager.GetString("OperationCancelled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 pack 的本地化字符串。
        /// </summary>
        internal static string OperationPack {
            get {
                return ResourceManager.GetString("OperationPack", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 unpack 的本地化字符串。
        /// </summary>
        internal static string OperationUnpack {
            get {
                return ResourceManager.GetString("OperationUnpack", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Processing file: {0} 的本地化字符串。
        /// </summary>
        internal static string ProcessingFile {
            get {
                return ResourceManager.GetString("ProcessingFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Processing folder: {0} 的本地化字符串。
        /// </summary>
        internal static string ProcessingFolder {
            get {
                return ResourceManager.GetString("ProcessingFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Seed 的本地化字符串。
        /// </summary>
        internal static string Seed {
            get {
                return ResourceManager.GetString("Seed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Starting {0}ing... 的本地化字符串。
        /// </summary>
        internal static string StartingOperation {
            get {
                return ResourceManager.GetString("StartingOperation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Packing succeeded. 的本地化字符串。
        /// </summary>
        internal static string SuccessPack {
            get {
                return ResourceManager.GetString("SuccessPack", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Unpacking succeeded. 的本地化字符串。
        /// </summary>
        internal static string SuccessUnpack {
            get {
                return ResourceManager.GetString("SuccessUnpack", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Try to decompress {0} with {1}…… 的本地化字符串。
        /// </summary>
        internal static string TryDecompressWithMethod {
            get {
                return ResourceManager.GetString("TryDecompressWithMethod", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Valid {0} v{1} archive detected. 的本地化字符串。
        /// </summary>
        internal static string ValidArchiveDetected {
            get {
                return ResourceManager.GetString("ValidArchiveDetected", resourceCulture);
            }
        }
    }
}
