//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace GalArc.Strings {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class GUIStrings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal GUIStrings() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("GalArc.Strings.GUIStrings", typeof(GUIStrings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   重写当前线程的 CurrentUICulture 属性，对
        ///   使用此强类型资源类的所有资源查找执行重写。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 Engine Name 的本地化字符串。
        /// </summary>
        public static string columnEngineName {
            get {
                return ResourceManager.GetString("columnEngineName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Pack Format 的本地化字符串。
        /// </summary>
        public static string columnPackFormat {
            get {
                return ResourceManager.GetString("columnPackFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Unpack Format 的本地化字符串。
        /// </summary>
        public static string columnUnpackFormat {
            get {
                return ResourceManager.GetString("columnUnpackFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Contents: 的本地化字符串。
        /// </summary>
        public static string InfoContents {
            get {
                return ResourceManager.GetString("InfoContents", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Disabled. 的本地化字符串。
        /// </summary>
        public static string InfoDisabled {
            get {
                return ResourceManager.GetString("InfoDisabled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Name: {0} 的本地化字符串。
        /// </summary>
        public static string InfoEngineName {
            get {
                return ResourceManager.GetString("InfoEngineName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Failed to read information. 的本地化字符串。
        /// </summary>
        public static string InfoFailedToReadInfos {
            get {
                return ResourceManager.GetString("InfoFailedToReadInfos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Specified file not found. 的本地化字符串。
        /// </summary>
        public static string InfoFileNotFound {
            get {
                return ResourceManager.GetString("InfoFileNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 {0}: {1} items 的本地化字符串。
        /// </summary>
        public static string InfoItems {
            get {
                return ResourceManager.GetString("InfoItems", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Last modified time: {0} 的本地化字符串。
        /// </summary>
        public static string InfoLastModified {
            get {
                return ResourceManager.GetString("InfoLastModified", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Size: {0} bytes 的本地化字符串。
        /// </summary>
        public static string InfoSize {
            get {
                return ResourceManager.GetString("InfoSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Custom encryption scheme 的本地化字符串。
        /// </summary>
        public static string ItemCustomEnc {
            get {
                return ResourceManager.GetString("ItemCustomEnc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Default encryption scheme 的本地化字符串。
        /// </summary>
        public static string ItemDefaultEnc {
            get {
                return ResourceManager.GetString("ItemDefaultEnc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 No encryption 的本地化字符串。
        /// </summary>
        public static string ItemNoEnc {
            get {
                return ResourceManager.GetString("ItemNoEnc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Try every encryption scheme 的本地化字符串。
        /// </summary>
        public static string ItemTryEveryEnc {
            get {
                return ResourceManager.GetString("ItemTryEveryEnc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Version {0} 的本地化字符串。
        /// </summary>
        public static string lbVersion {
            get {
                return ResourceManager.GetString("lbVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Database 的本地化字符串。
        /// </summary>
        public static string nodeDatabase {
            get {
                return ResourceManager.GetString("nodeDatabase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 General 的本地化字符串。
        /// </summary>
        public static string nodeGeneral {
            get {
                return ResourceManager.GetString("nodeGeneral", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Log 的本地化字符串。
        /// </summary>
        public static string nodeLog {
            get {
                return ResourceManager.GetString("nodeLog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Preference 的本地化字符串。
        /// </summary>
        public static string nodePreference {
            get {
                return ResourceManager.GetString("nodePreference", resourceCulture);
            }
        }
    }
}
