//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace GalArc.Strings {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class LogStrings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal LogStrings() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("GalArc.Strings.LogStrings", typeof(LogStrings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   重写当前线程的 CurrentUICulture 属性，对
        ///   使用此强类型资源类的所有资源查找执行重写。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 Compression method: {0} 的本地化字符串。
        /// </summary>
        public static string ArcComprMethod {
            get {
                return ResourceManager.GetString("ArcComprMethod", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Version: {0} 的本地化字符串。
        /// </summary>
        public static string ArcVersion {
            get {
                return ResourceManager.GetString("ArcVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Batch extraction activated. 的本地化字符串。
        /// </summary>
        public static string BatchActivated {
            get {
                return ResourceManager.GetString("BatchActivated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Matched file count: {0} 的本地化字符串。
        /// </summary>
        public static string BatchMatchFiles {
            get {
                return ResourceManager.GetString("BatchMatchFiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Batch extraction finished. {0} among {1} were unpacked successfully. 的本地化字符串。
        /// </summary>
        public static string BatchUnpackFinish {
            get {
                return ResourceManager.GetString("BatchUnpackFinish", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Error: Index offset not found. 的本地化字符串。
        /// </summary>
        public static string BrutalForceFailed {
            get {
                return ResourceManager.GetString("BrutalForceFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Brutal forcing…… 的本地化字符串。
        /// </summary>
        public static string BrutalForcing {
            get {
                return ResourceManager.GetString("BrutalForcing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Error: {0} 的本地化字符串。
        /// </summary>
        public static string Error {
            get {
                return ResourceManager.GetString("Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Path contains invalid characters. Switching the encoding in the settings might work. 的本地化字符串。
        /// </summary>
        public static string ErrorContainsInvalid {
            get {
                return ResourceManager.GetString("ErrorContainsInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Decompression failed. 的本地化字符串。
        /// </summary>
        public static string ErrorDecompressFailed {
            get {
                return ResourceManager.GetString("ErrorDecompressFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Decryption failed. 的本地化字符串。
        /// </summary>
        public static string ErrorDecScrFailed {
            get {
                return ResourceManager.GetString("ErrorDecScrFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Folder specified does not exist. 的本地化字符串。
        /// </summary>
        public static string ErrorDirNotFound {
            get {
                return ResourceManager.GetString("ErrorDirNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Encryption failed. 的本地化字符串。
        /// </summary>
        public static string ErrorEncScrFailed {
            get {
                return ResourceManager.GetString("ErrorEncScrFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 File name must be {0}. 的本地化字符串。
        /// </summary>
        public static string ErrorFileNameFailToMatch {
            get {
                return ResourceManager.GetString("ErrorFileNameFailToMatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 File specified does not exist. 的本地化字符串。
        /// </summary>
        public static string ErrorFileNotFound {
            get {
                return ResourceManager.GetString("ErrorFileNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Failed to import schemes. 的本地化字符串。
        /// </summary>
        public static string ErrorImportScheme {
            get {
                return ResourceManager.GetString("ErrorImportScheme", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Invalid archive. 的本地化字符串。
        /// </summary>
        public static string ErrorInvalidArchive {
            get {
                return ResourceManager.GetString("ErrorInvalidArchive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Invalid archive: {0} 的本地化字符串。
        /// </summary>
        public static string ErrorInvalidArchiveCaption {
            get {
                return ResourceManager.GetString("ErrorInvalidArchiveCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Error: Invalid index offset. 的本地化字符串。
        /// </summary>
        public static string ErrorInvalidIndexOffset {
            get {
                return ResourceManager.GetString("ErrorInvalidIndexOffset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Invalid encryption scheme. 的本地化字符串。
        /// </summary>
        public static string ErrorInvalidScheme {
            get {
                return ResourceManager.GetString("ErrorInvalidScheme", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Unknown or not supported archive version. 的本地化字符串。
        /// </summary>
        public static string ErrorInvalidVersion {
            get {
                return ResourceManager.GetString("ErrorInvalidVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 {0} v{1} archive temporarily not supported. 的本地化字符串。
        /// </summary>
        public static string ErrorInvalidVersionNotSupported {
            get {
                return ResourceManager.GetString("ErrorInvalidVersionNotSupported", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Unknown version. 的本地化字符串。
        /// </summary>
        public static string ErrorInvalidVersionUnknown {
            get {
                return ResourceManager.GetString("ErrorInvalidVersionUnknown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Please select operation. 的本地化字符串。
        /// </summary>
        public static string ErrorNeedSelectOperation {
            get {
                return ResourceManager.GetString("ErrorNeedSelectOperation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Please specify input path. 的本地化字符串。
        /// </summary>
        public static string ErrorNeedSpecifyInput {
            get {
                return ResourceManager.GetString("ErrorNeedSpecifyInput", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Please specify output path. 的本地化字符串。
        /// </summary>
        public static string ErrorNeedSpecifyOutput {
            get {
                return ResourceManager.GetString("ErrorNeedSpecifyOutput", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Original {0} file not found in the same directory. 的本地化字符串。
        /// </summary>
        public static string ErrorOriginalFileNotFound {
            get {
                return ResourceManager.GetString("ErrorOriginalFileNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 {0} file not found in the same directory. 的本地化字符串。
        /// </summary>
        public static string ErrorSpecifiedFileNotFound {
            get {
                return ResourceManager.GetString("ErrorSpecifiedFileNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Exit the instance 的本地化字符串。
        /// </summary>
        public static string Exit {
            get {
                return ResourceManager.GetString("Exit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 {0} files inside. 的本地化字符串。
        /// </summary>
        public static string FileCountInside {
            get {
                return ResourceManager.GetString("FileCountInside", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 New update available! 的本地化字符串。
        /// </summary>
        public static string HasUpdate {
            get {
                return ResourceManager.GetString("HasUpdate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Index offset: {0} 的本地化字符串。
        /// </summary>
        public static string IndexOffset {
            get {
                return ResourceManager.GetString("IndexOffset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Input file path: 的本地化字符串。
        /// </summary>
        public static string InputFile {
            get {
                return ResourceManager.GetString("InputFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Input folder path: 的本地化字符串。
        /// </summary>
        public static string InputFolder {
            get {
                return ResourceManager.GetString("InputFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Error: Invalid archive type. 的本地化字符串。
        /// </summary>
        public static string InvalidArchiveType {
            get {
                return ResourceManager.GetString("InvalidArchiveType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Key: {0} 的本地化字符串。
        /// </summary>
        public static string Key {
            get {
                return ResourceManager.GetString("Key", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Key found: {0} 的本地化字符串。
        /// </summary>
        public static string KeyFound {
            get {
                return ResourceManager.GetString("KeyFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Key not found. 的本地化字符串。
        /// </summary>
        public static string KeyNotFound {
            get {
                return ResourceManager.GetString("KeyNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Failed to parse key. 的本地化字符串。
        /// </summary>
        public static string KeyParseError {
            get {
                return ResourceManager.GetString("KeyParseError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Matched game: {0} 的本地化字符串。
        /// </summary>
        public static string MatchedGame {
            get {
                return ResourceManager.GetString("MatchedGame", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The file has been encrypted. Please choose appropriate scheme. 的本地化字符串。
        /// </summary>
        public static string NeedDec {
            get {
                return ResourceManager.GetString("NeedDec", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 New Instance 的本地化字符串。
        /// </summary>
        public static string NewInstance {
            get {
                return ResourceManager.GetString("NewInstance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 You are using the latest version of GalArc. 的本地化字符串。
        /// </summary>
        public static string NoUpdate {
            get {
                return ResourceManager.GetString("NoUpdate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Output file path: 的本地化字符串。
        /// </summary>
        public static string OutputFile {
            get {
                return ResourceManager.GetString("OutputFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Output folder path: 的本地化字符串。
        /// </summary>
        public static string OutputFolder {
            get {
                return ResourceManager.GetString("OutputFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Packing failed: {0} 的本地化字符串。
        /// </summary>
        public static string PackFailed {
            get {
                return ResourceManager.GetString("PackFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Packing…… 的本地化字符串。
        /// </summary>
        public static string Packing {
            get {
                return ResourceManager.GetString("Packing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Packing {0}… 的本地化字符串。
        /// </summary>
        public static string PackingFile {
            get {
                return ResourceManager.GetString("PackingFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Packing finished. 的本地化字符串。
        /// </summary>
        public static string PackSuccess {
            get {
                return ResourceManager.GetString("PackSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 You are using a pre-release version of GalArc. 的本地化字符串。
        /// </summary>
        public static string PreReleaseVer {
            get {
                return ResourceManager.GetString("PreReleaseVer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Ready 的本地化字符串。
        /// </summary>
        public static string Ready {
            get {
                return ResourceManager.GetString("Ready", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Scheme count: {0} 的本地化字符串。
        /// </summary>
        public static string SchemeCount {
            get {
                return ResourceManager.GetString("SchemeCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Loaded schemes: {0} 的本地化字符串。
        /// </summary>
        public static string SchemeLoadedCount {
            get {
                return ResourceManager.GetString("SchemeLoadedCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 {0}: Load {1} schemes. 的本地化字符串。
        /// </summary>
        public static string SchemeLoadedNameCount {
            get {
                return ResourceManager.GetString("SchemeLoadedNameCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Done. {0} schemes were loaded in total. 的本地化字符串。
        /// </summary>
        public static string SchemeLoadedWithCount {
            get {
                return ResourceManager.GetString("SchemeLoadedWithCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Loading schemes…… 的本地化字符串。
        /// </summary>
        public static string SchemeLoading {
            get {
                return ResourceManager.GetString("SchemeLoading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Done. 的本地化字符串。
        /// </summary>
        public static string SchemeRefreshed {
            get {
                return ResourceManager.GetString("SchemeRefreshed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Refreshing interface…… 的本地化字符串。
        /// </summary>
        public static string SchemeRefreshing {
            get {
                return ResourceManager.GetString("SchemeRefreshing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Seed: {0} 的本地化字符串。
        /// </summary>
        public static string Seed {
            get {
                return ResourceManager.GetString("Seed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Pack mode: {0} {1} selected. 的本地化字符串。
        /// </summary>
        public static string SelectPackNode {
            get {
                return ResourceManager.GetString("SelectPackNode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Unpack mode: {0} {1} selected. 的本地化字符串。
        /// </summary>
        public static string SelectUnpackNode {
            get {
                return ResourceManager.GetString("SelectUnpackNode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Timed out. 的本地化字符串。
        /// </summary>
        public static string TimedOut {
            get {
                return ResourceManager.GetString("TimedOut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Try to decompress: {0}…… 的本地化字符串。
        /// </summary>
        public static string TryDecompress {
            get {
                return ResourceManager.GetString("TryDecompress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Try to decompress {0} with {1}…… 的本地化字符串。
        /// </summary>
        public static string TryDecompressWithMethod {
            get {
                return ResourceManager.GetString("TryDecompressWithMethod", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Try to decrypt: {0}…… 的本地化字符串。
        /// </summary>
        public static string TryDecScr {
            get {
                return ResourceManager.GetString("TryDecScr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Try to encrypt: {0}…… 的本地化字符串。
        /// </summary>
        public static string TryEncScr {
            get {
                return ResourceManager.GetString("TryEncScr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Unpacking failed: {0} 的本地化字符串。
        /// </summary>
        public static string UnpackFailed {
            get {
                return ResourceManager.GetString("UnpackFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Unpacking…… 的本地化字符串。
        /// </summary>
        public static string Unpacking {
            get {
                return ResourceManager.GetString("Unpacking", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Unpacking {0}… 的本地化字符串。
        /// </summary>
        public static string UnpackingFile {
            get {
                return ResourceManager.GetString("UnpackingFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Unpacking finished. 的本地化字符串。
        /// </summary>
        public static string UnpackSuccess {
            get {
                return ResourceManager.GetString("UnpackSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Failed to check for updates. 的本地化字符串。
        /// </summary>
        public static string UpdateError {
            get {
                return ResourceManager.GetString("UpdateError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Checking for updates…… 的本地化字符串。
        /// </summary>
        public static string Updating {
            get {
                return ResourceManager.GetString("Updating", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Valid {0} v{1} archive detected. 的本地化字符串。
        /// </summary>
        public static string ValidArchiveDetected {
            get {
                return ResourceManager.GetString("ValidArchiveDetected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Valid database count: {0} 的本地化字符串。
        /// </summary>
        public static string ValidDatabaseCount {
            get {
                return ResourceManager.GetString("ValidDatabaseCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Current version: {0} Latest version: {1} 的本地化字符串。
        /// </summary>
        public static string Versions {
            get {
                return ResourceManager.GetString("Versions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Wrong scheme! 的本地化字符串。
        /// </summary>
        public static string WrongScheme {
            get {
                return ResourceManager.GetString("WrongScheme", resourceCulture);
            }
        }
    }
}
