//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace GalArc.Strings {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class LogStrings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal LogStrings() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("GalArc.Strings.LogStrings", typeof(LogStrings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   重写当前线程的 CurrentUICulture 属性，对
        ///   使用此强类型资源类的所有资源查找执行重写。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 Error: Not a valid archive. 的本地化字符串。
        /// </summary>
        internal static string ErrorNotValidArc {
            get {
                return ResourceManager.GetString("ErrorNotValidArc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Error: {0} 的本地化字符串。
        /// </summary>
        internal static string ErrorOccur {
            get {
                return ResourceManager.GetString("ErrorOccur", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Error: Original {0} file not found in the same directory. 的本地化字符串。
        /// </summary>
        internal static string ErrorOriginalFileNotFound {
            get {
                return ResourceManager.GetString("ErrorOriginalFileNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Error: {0} file not found in the same directory. 的本地化字符串。
        /// </summary>
        internal static string ErrorSpecifiedFileNotFound {
            get {
                return ResourceManager.GetString("ErrorSpecifiedFileNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 {0} files inside. 的本地化字符串。
        /// </summary>
        internal static string FileCountInside {
            get {
                return ResourceManager.GetString("FileCountInside", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 New update available! 的本地化字符串。
        /// </summary>
        internal static string HasUpdate {
            get {
                return ResourceManager.GetString("HasUpdate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Import {0} schemes from Database. 的本地化字符串。
        /// </summary>
        internal static string ImportDataBaseScheme {
            get {
                return ResourceManager.GetString("ImportDataBaseScheme", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Import {0} schemes from GARbroDB. 的本地化字符串。
        /// </summary>
        internal static string ImportGARbroDBScheme {
            get {
                return ResourceManager.GetString("ImportGARbroDBScheme", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Input file path: 的本地化字符串。
        /// </summary>
        internal static string InputFile {
            get {
                return ResourceManager.GetString("InputFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Input folder path: 的本地化字符串。
        /// </summary>
        internal static string InputFolder {
            get {
                return ResourceManager.GetString("InputFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 New Instance 的本地化字符串。
        /// </summary>
        internal static string NewInstance {
            get {
                return ResourceManager.GetString("NewInstance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 You are using the latest version of GalArc. 的本地化字符串。
        /// </summary>
        internal static string NoUpdate {
            get {
                return ResourceManager.GetString("NoUpdate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Output file path: 的本地化字符串。
        /// </summary>
        internal static string OutputFile {
            get {
                return ResourceManager.GetString("OutputFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Output folder path: 的本地化字符串。
        /// </summary>
        internal static string OutputFolder {
            get {
                return ResourceManager.GetString("OutputFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Pack finished. 的本地化字符串。
        /// </summary>
        internal static string PackFinished {
            get {
                return ResourceManager.GetString("PackFinished", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Packing…… 的本地化字符串。
        /// </summary>
        internal static string Packing {
            get {
                return ResourceManager.GetString("Packing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Unpack finished. 的本地化字符串。
        /// </summary>
        internal static string UnpackFinished {
            get {
                return ResourceManager.GetString("UnpackFinished", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Unpacking…… 的本地化字符串。
        /// </summary>
        internal static string Unpacking {
            get {
                return ResourceManager.GetString("Unpacking", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Error occurs while checking for update. 的本地化字符串。
        /// </summary>
        internal static string UpdateError {
            get {
                return ResourceManager.GetString("UpdateError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Checking for update…… 的本地化字符串。
        /// </summary>
        internal static string Updating {
            get {
                return ResourceManager.GetString("Updating", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Valid {0} v{1} archive detected. 的本地化字符串。
        /// </summary>
        internal static string ValidArchiveDetected {
            get {
                return ResourceManager.GetString("ValidArchiveDetected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Current version: {0} Latest version: {1} 的本地化字符串。
        /// </summary>
        internal static string Versions {
            get {
                return ResourceManager.GetString("Versions", resourceCulture);
            }
        }
    }
}
