//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace GalArc.Strings {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class LogStrings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal LogStrings() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("GalArc.Strings.LogStrings", typeof(LogStrings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   重写当前线程的 CurrentUICulture 属性，对
        ///   使用此强类型资源类的所有资源查找执行重写。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 Specified class not found. 的本地化字符串。
        /// </summary>
        public static string ErrorClassNotFound {
            get {
                return ResourceManager.GetString("ErrorClassNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Folder specified does not exist. 的本地化字符串。
        /// </summary>
        public static string ErrorDirNotFound {
            get {
                return ResourceManager.GetString("ErrorDirNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 File name must be {0}. 的本地化字符串。
        /// </summary>
        public static string ErrorFileNameFailToMatch {
            get {
                return ResourceManager.GetString("ErrorFileNameFailToMatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 File specified does not exist. 的本地化字符串。
        /// </summary>
        public static string ErrorFileNotFound {
            get {
                return ResourceManager.GetString("ErrorFileNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Please select operation. 的本地化字符串。
        /// </summary>
        public static string ErrorNeedSelectOperation {
            get {
                return ResourceManager.GetString("ErrorNeedSelectOperation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Please specify input path. 的本地化字符串。
        /// </summary>
        public static string ErrorNeedSpecifyInput {
            get {
                return ResourceManager.GetString("ErrorNeedSpecifyInput", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Please specify output path. 的本地化字符串。
        /// </summary>
        public static string ErrorNeedSpecifyOutput {
            get {
                return ResourceManager.GetString("ErrorNeedSpecifyOutput", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Not a valid archive. 的本地化字符串。
        /// </summary>
        public static string ErrorNotValidArc {
            get {
                return ResourceManager.GetString("ErrorNotValidArc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Error: {0} 的本地化字符串。
        /// </summary>
        public static string ErrorOccur {
            get {
                return ResourceManager.GetString("ErrorOccur", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Original {0} file not found in the same directory. 的本地化字符串。
        /// </summary>
        public static string ErrorOriginalFileNotFound {
            get {
                return ResourceManager.GetString("ErrorOriginalFileNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Specified pack method not found. 的本地化字符串。
        /// </summary>
        public static string ErrorPackMethodNotFound {
            get {
                return ResourceManager.GetString("ErrorPackMethodNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 {0} file not found in the same directory. 的本地化字符串。
        /// </summary>
        public static string ErrorSpecifiedFileNotFound {
            get {
                return ResourceManager.GetString("ErrorSpecifiedFileNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Specified unpack method not found. 的本地化字符串。
        /// </summary>
        public static string ErrorUnpackMethodNotFound {
            get {
                return ResourceManager.GetString("ErrorUnpackMethodNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 {0} files inside. 的本地化字符串。
        /// </summary>
        public static string FileCountInside {
            get {
                return ResourceManager.GetString("FileCountInside", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 New update available! 的本地化字符串。
        /// </summary>
        public static string HasUpdate {
            get {
                return ResourceManager.GetString("HasUpdate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 {0}: Import {1} schemes. 的本地化字符串。
        /// </summary>
        public static string ImportDataBaseScheme {
            get {
                return ResourceManager.GetString("ImportDataBaseScheme", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Imported scheme count: {0} 的本地化字符串。
        /// </summary>
        public static string ImportedSchemeCount {
            get {
                return ResourceManager.GetString("ImportedSchemeCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Import {0} schemes from GARbroDB. 的本地化字符串。
        /// </summary>
        public static string ImportGARbroDBScheme {
            get {
                return ResourceManager.GetString("ImportGARbroDBScheme", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Input file path: 的本地化字符串。
        /// </summary>
        public static string InputFile {
            get {
                return ResourceManager.GetString("InputFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Input folder path: 的本地化字符串。
        /// </summary>
        public static string InputFolder {
            get {
                return ResourceManager.GetString("InputFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Loading…… 的本地化字符串。
        /// </summary>
        public static string Loading {
            get {
                return ResourceManager.GetString("Loading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 New Instance 的本地化字符串。
        /// </summary>
        public static string NewInstance {
            get {
                return ResourceManager.GetString("NewInstance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 You are using the latest version of GalArc. 的本地化字符串。
        /// </summary>
        public static string NoUpdate {
            get {
                return ResourceManager.GetString("NoUpdate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Output file path: 的本地化字符串。
        /// </summary>
        public static string OutputFile {
            get {
                return ResourceManager.GetString("OutputFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Output folder path: 的本地化字符串。
        /// </summary>
        public static string OutputFolder {
            get {
                return ResourceManager.GetString("OutputFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Pack finished. 的本地化字符串。
        /// </summary>
        public static string PackFinished {
            get {
                return ResourceManager.GetString("PackFinished", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Packing…… 的本地化字符串。
        /// </summary>
        public static string Packing {
            get {
                return ResourceManager.GetString("Packing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Ready 的本地化字符串。
        /// </summary>
        public static string Ready {
            get {
                return ResourceManager.GetString("Ready", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Scheme count: {0} 的本地化字符串。
        /// </summary>
        public static string SchemeCount {
            get {
                return ResourceManager.GetString("SchemeCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Pack mode: {0} {1} selected. 的本地化字符串。
        /// </summary>
        public static string SelectPackNode {
            get {
                return ResourceManager.GetString("SelectPackNode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Unpack mode: {0} {1} selected. 的本地化字符串。
        /// </summary>
        public static string SelectUnpackNode {
            get {
                return ResourceManager.GetString("SelectUnpackNode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Timed out. 的本地化字符串。
        /// </summary>
        public static string TimedOut {
            get {
                return ResourceManager.GetString("TimedOut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Unpack finished. 的本地化字符串。
        /// </summary>
        public static string UnpackFinished {
            get {
                return ResourceManager.GetString("UnpackFinished", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Unpacking…… 的本地化字符串。
        /// </summary>
        public static string Unpacking {
            get {
                return ResourceManager.GetString("Unpacking", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Failed to check for updates. 的本地化字符串。
        /// </summary>
        public static string UpdateError {
            get {
                return ResourceManager.GetString("UpdateError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Checking for updates…… 的本地化字符串。
        /// </summary>
        public static string Updating {
            get {
                return ResourceManager.GetString("Updating", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Valid {0} v{1} archive detected. 的本地化字符串。
        /// </summary>
        public static string ValidArchiveDetected {
            get {
                return ResourceManager.GetString("ValidArchiveDetected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Valid database count: {0} 的本地化字符串。
        /// </summary>
        public static string ValidDatabaseCount {
            get {
                return ResourceManager.GetString("ValidDatabaseCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Current version: {0} Latest version: {1} 的本地化字符串。
        /// </summary>
        public static string Versions {
            get {
                return ResourceManager.GetString("Versions", resourceCulture);
            }
        }
    }
}
