//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Log.Properties {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Log.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   重写当前线程的 CurrentUICulture 属性，对
        ///   使用此强类型资源类的所有资源查找执行重写。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 Error: Not a valid archive. 的本地化字符串。
        /// </summary>
        internal static string logErrorNotValidArc {
            get {
                return ResourceManager.GetString("logErrorNotValidArc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Error occurs. Please refer to log for detail. 的本地化字符串。
        /// </summary>
        internal static string logErrorOccur {
            get {
                return ResourceManager.GetString("logErrorOccur", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Error: Original {0} file not found. 的本地化字符串。
        /// </summary>
        internal static string logErrorOriginalFileNotFound {
            get {
                return ResourceManager.GetString("logErrorOriginalFileNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Error: {0} and {1} file with the same name should be in the same directory. 的本地化字符串。
        /// </summary>
        internal static string logErrorSameNameNotFound {
            get {
                return ResourceManager.GetString("logErrorSameNameNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 {0} files inside. 的本地化字符串。
        /// </summary>
        internal static string logFileCountInside {
            get {
                return ResourceManager.GetString("logFileCountInside", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 New update available! 的本地化字符串。
        /// </summary>
        internal static string logHasUpdate {
            get {
                return ResourceManager.GetString("logHasUpdate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Input file path: 的本地化字符串。
        /// </summary>
        internal static string logInputFile {
            get {
                return ResourceManager.GetString("logInputFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Input folder path: 的本地化字符串。
        /// </summary>
        internal static string logInputFolder {
            get {
                return ResourceManager.GetString("logInputFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 New Instance 的本地化字符串。
        /// </summary>
        internal static string logNewInstance {
            get {
                return ResourceManager.GetString("logNewInstance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 (no extension) 的本地化字符串。
        /// </summary>
        internal static string logNoExtension {
            get {
                return ResourceManager.GetString("logNoExtension", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 You are using the latest version of GalArc. 的本地化字符串。
        /// </summary>
        internal static string logNoUpdate {
            get {
                return ResourceManager.GetString("logNoUpdate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Output file path: 的本地化字符串。
        /// </summary>
        internal static string logOutputFile {
            get {
                return ResourceManager.GetString("logOutputFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Output folder path: 的本地化字符串。
        /// </summary>
        internal static string logOutputFolder {
            get {
                return ResourceManager.GetString("logOutputFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Pack finished. 的本地化字符串。
        /// </summary>
        internal static string logPackFinished {
            get {
                return ResourceManager.GetString("logPackFinished", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Packing…… 的本地化字符串。
        /// </summary>
        internal static string logPacking {
            get {
                return ResourceManager.GetString("logPacking", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Unpack finished. 的本地化字符串。
        /// </summary>
        internal static string logUnpackFinished {
            get {
                return ResourceManager.GetString("logUnpackFinished", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Unpacking…… 的本地化字符串。
        /// </summary>
        internal static string logUnpacking {
            get {
                return ResourceManager.GetString("logUnpacking", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Error occurs while checking for update. 的本地化字符串。
        /// </summary>
        internal static string logUpdateError {
            get {
                return ResourceManager.GetString("logUpdateError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Checking for update…… 的本地化字符串。
        /// </summary>
        internal static string logUpdating {
            get {
                return ResourceManager.GetString("logUpdating", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Valid {0} v{1} archive detected. 的本地化字符串。
        /// </summary>
        internal static string logValidArchiveDetected {
            get {
                return ResourceManager.GetString("logValidArchiveDetected", resourceCulture);
            }
        }
    }
}
